version: 2
jobs:
  build:
    working_directory: ~/minisaml
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - run:
          $HOME/.poetry/bin/poetry install
      - run:
          $HOME/.poetry/bin/poetry run pytest
      - run:
          $HOME/.poetry/bin/poetry run black --check
      - run:
          $HOME/.poetry/bin/poetry run isort --check-only
